from enum import Enum


class authResponses(Enum):
    class base:
        SUCCESS = 'SUCCESS'
        INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'

    class middleware(base):
        ERROR_ROUTE_NOT_FOUND = 'ERROR_ROUTE_NOT_FOUND'
        ERROR_INVALID_SESSION = 'ERROR_INVALID_SESSION'
        ERROR_INVALID_CSRF_TOKEN = 'ERROR_INVALID_CSRF_TOKEN'  # nosec: B105

    class googleLogin(base):
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_INVALID_LOGIN_METHOD = 'ERROR_INVALID_LOGIN_METHOD'
        ERROR_INVALID_RESULT_FROM_DB = 'ERROR_INVALID_RESULT_FROM_DB'

    class getCredentials(base):
        SUCCESS_NEW_PRELOGIN_SESSION = 'SUCCESS_NEW_PRELOGIN_SESSION'
        SUCCESS_EXISTING_PRELOGIN_SESSION = 'SUCCESS_EXISTING_PRELOGIN_SESSION'
        SUCCESS_EXISTING_POSTLOGIN_SESSION = 'SUCCESS_EXISTING_POSTLOGIN_SESSION'

        ERROR_RATE_LIMIT_EXCEEDED = 'ERROR_RATE_LIMIT_EXCEEDED'
        ERROR_INVALID_DB_RESULT_FOR_POSTLOGIN = 'ERROR_INVALID_DB_RESULT_FOR_POSTLOGIN'
        ERROR_MALFORMED_SERVER_SESSION = 'ERROR_MALFORMED_SERVER_SESSION'

    class signIn(base):
        ERROR_RATE_LIMIT_EXCEEDED = 'ERROR_RATE_LIMIT_EXCEEDED'
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_USER_DOESNT_EXISTS = 'ERROR_USER_DOESNT_EXISTS'
        ERROR_INVALID_LOGIN_METHOD = 'ERROR_INVALID_LOGIN_METHOD'
        ERROR_INVALID_GETCREDENTIALS_DATA = 'ERROR_INVALID_GETCREDENTIALS_DATA'
        ERROR_UNACTIVATED_ACCOUNT = 'ERROR_UNACTIVATED_ACCOUNT'
        ERROR_INCORRECT_PASSWORD = 'ERROR_INCORRECT_PASSWORD'  # nosec: B105
        ERROR_INVALID_PATCH_FROM_DB = 'ERROR_INVALID_PATCH_FROM_DB'

    class signUp(base):
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_EMAIL_ALREADY_EXISTS = 'ERROR_EMAIL_ALREADY_EXISTS'
        ERROR_INVALID_PATCH_FROM_DB = 'ERROR_INVALID_PATCH_FROM_DB'
        ERROR_RATE_LIMIT_EXCEEDED = 'ERROR_RATE_LIMIT_EXCEEDED'

    class activateAccount(base):
        ERROR_INVALID_QUERY_STRING = 'ERROR_INVALID_QUERY_STRING'
        ERROR_EMAIL_DOESNT_EXISTS_OR_ACTIVATED = 'ERROR_EMAIL_DOESNT_EXISTS_OR_ACTIVATED'
        ERROR_INVALID_PATCH_FROM_DB = 'ERROR_INVALID_PATCH_FROM_DB'

    class requestForgotPassword(base):
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_EMAIL_DOESNT_EXISTS = 'ERROR_EMAIL_DOESNT_EXISTS'
        ERROR_INVALID_PATCH_FROM_DB = 'ERROR_INVALID_PATCH_FROM_DB'
        ERROR_RATE_LIMIT_EXCEEDED = 'ERROR_RATE_LIMIT_EXCEEDED'

    class resetPassword(base):
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_INVALID_QUERY_STRING = 'ERROR_INVALID_QUERY_STRING'
        ERROR_INVALID_TOKEN_OR_EMAIL_DOESNT_EXISTS = 'ERROR_INVALID_TOKEN_OR_EMAIL_DOESNT_EXISTS'  # nosec: B105
        ERROR_RESET_WINDOW_EXPIRED = 'ERROR_RESET_WINDOW_EXPIRED'
        ERROR_INVALID_PATCH_FROM_DB = 'ERROR_INVALID_PATCH_FROM_DB'

    class logout(base):
        ERROR_UNAUTHENTICATED_SESSION = 'ERROR_UNAUTHENTICATED_SESSION'

    class deleteAccount(base):
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_UNAUTHENTICATED_SESSION = 'ERROR_UNAUTHENTICATED_SESSION'