from enum import Enum


class transactionResponses(Enum):
    class base:
        SUCCESS = 'SUCCESS'
        INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'

    class getAllTransactions(base):
        SUCCESS_NO_REFETCH_NEEDED = 'SUCCESS_NO_REFETCH_NEEDED'
        SUCCESS_FETCHED = 'SUCCESS_FETCHED'

        ERROR_UNAUTHENTICATED_SESSION = 'ERROR_UNAUTHENTICATED_SESSION'
        ERROR_INVALID_GET_FROM_DB = 'ERROR_INVALID_GET_FROM_DB'

    class addTransaction(base):
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_UNAUTHENTICATED_SESSION = 'ERROR_UNAUTHENTICATED_SESSION'

    class deleteOne(base):
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_UNAUTHENTICATED_SESSION = 'ERROR_UNAUTHENTICATED_SESSION'

    class deleteMany(base):
        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_UNAUTHENTICATED_SESSION = 'ERROR_UNAUTHENTICATED_SESSION'

    class update(base):
        SUCCESS_NO_UPDATE = 'SUCCESS_NO_UPDATE'
        SUCCESS_UPDATED = 'SUCCESS_UPDATED'

        ERROR_INVALID_REQUEST_BODY = 'ERROR_INVALID_REQUEST_BODY'
        ERROR_UNAUTHENTICATED_SESSION = 'ERROR_UNAUTHENTICATED_SESSION'
        